language: node_js

sudo: required

cache:
  directories:
    - node_modules

services:
  - docker

before_install:
  - docker-compose up --no-start build

script:
  - docker-compose run build bash -c "npm run test"

before_deploy:
  - docker-compose run build bash -c "npm run build"

deploy:
  skip_cleanup: true
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_API_TOKEN
  on:
    tags: true

after_deploy:
  - docker-compose run --rm build bin/announce
