// flow-typed signature: c9049d595aed23bb90deaaccdad196a1
// flow-typed version: <<STUB>>/prismic-reactjs_v^0.2.3/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'prismic-reactjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'prismic-reactjs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'prismic-reactjs/dist/prismic-reactjs' {
  declare module.exports: any;
}

declare module 'prismic-reactjs/dist/prismic-reactjs.min' {
  declare module.exports: any;
}

declare module 'prismic-reactjs/src/index' {
  declare module.exports: any;
}

declare module 'prismic-reactjs/src/richtext' {
  declare module.exports: any;
}

declare module 'prismic-reactjs/src/uuid' {
  declare module.exports: any;
}

declare module 'prismic-reactjs/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'prismic-reactjs/dist/prismic-reactjs.js' {
  declare module.exports: $Exports<'prismic-reactjs/dist/prismic-reactjs'>;
}
declare module 'prismic-reactjs/dist/prismic-reactjs.min.js' {
  declare module.exports: $Exports<'prismic-reactjs/dist/prismic-reactjs.min'>;
}
declare module 'prismic-reactjs/src/index.js' {
  declare module.exports: $Exports<'prismic-reactjs/src/index'>;
}
declare module 'prismic-reactjs/src/richtext.js' {
  declare module.exports: $Exports<'prismic-reactjs/src/richtext'>;
}
declare module 'prismic-reactjs/src/uuid.js' {
  declare module.exports: $Exports<'prismic-reactjs/src/uuid'>;
}
declare module 'prismic-reactjs/webpack.config.js' {
  declare module.exports: $Exports<'prismic-reactjs/webpack.config'>;
}
