---
steps:
  - type: "waiter"

  - name: ":nodejs: Test It"
    command: "docker-compose run --rm build bin/test"

  - wait

  - name: ":shipit: Deploy Documentation"
    command: "docker-compose run --rm build bin/only-for-version-releases bin/deploy-docs"
    branches: master

  - name: ":shipit: Deploy It"
    command: "docker-compose run --rm build bin/deploy"
    branches: master

  - wait

  - name: ":loudspeaker: Announce It"
    command: "./bin/announce"
    branches: master
